export const BUDGET_DETAILS_REQUEST = "BUDGET_DETAILS_REQUEST";
export const BUDGET_DETAILS_SUCCESS = "BUDGET_DETAILS_SUCCESS";
export const BUDGET_DETAILS_FAIL = "BUDGET_DETAILS_FAIL";

export const NEW_BUDGET_REQUEST = "NEW_BUDGET_REQUEST";
export const NEW_BUDGET_SUCCESS = "NEW_BUDGET_SUCCESS";
export const NEW_BUDGET_RESET = "NEW_BUDGET_RESET";
export const NEW_BUDGET_FAIL = "NEW_BUDGET_FAIL";

export const ADMIN_BUDGET_REQUEST = "ADMIN_BUDGETS_REQUEST";
export const ADMIN_BUDGET_SUCCESS = "ADMIN_BUDGETS_SUCCESS";
export const ADMIN_BUDGET_FAIL = "ADMIN_BUDGETS_FAIL";

export const DELETE_BUDGET_REQUEST = "DELETE_BUDGET_REQUEST";
export const DELETE_BUDGET_SUCCESS = "DELETE_BUDGET_SUCCESS";
export const DELETE_BUDGET_RESET = "DELETE_BUDGET_RESET";
export const DELETE_BUDGET_FAIL = "DELETE_BUDGET_FAIL";

export const UPDATE_BUDGET_REQUEST = "UPDATE_BUDGET_REQUEST";
export const UPDATE_BUDGET_SUCCESS = "UPDATE_BUDGET_SUCCESS";
export const UPDATE_BUDGET_RESET = "UPDATE_BUDGET_RESET";
export const UPDATE_BUDGET_FAIL = "UPDATE_BUDGET_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
