export const CASH_DETAILS_REQUEST = "CASH_ENTRY_DETAILS_REQUEST";
export const CASH_DETAILS_SUCCESS = "CASH_ENTRY_DETAILS_SUCCESS";
export const CASH_DETAILS_FAIL = "CASH_ENTRY_DETAILS_FAIL";
export const NEW_CASH_REQUEST = "NEW_CASH_ENTRY_REQUEST";
export const NEW_CASH_SUCCESS = "NEW_CASH_ENTRY_SUCCESS";
export const NEW_CASH_RESET = "NEW_CASH_ENTRY_RESET";
export const NEW_CASH_FAIL = "NEW_CASH_ENTRY_FAIL";
export const ADMIN_CASH_REQUEST = "ADMIN_CASH_ENTRIES_REQUEST";
export const ADMIN_CASH_SUCCESS = "ADMIN_CASH_ENTRIES_SUCCESS";
export const ADMIN_CASH_FAIL = "ADMIN_CASH_ENTRIES_FAIL";
export const DELETE_CASH_REQUEST = "DELETE_CASH_ENTRY_REQUEST";
export const DELETE_CASH_SUCCESS = "DELETE_CASH_ENTRY_SUCCESS";
export const DELETE_CASH_RESET = "DELETE_CASH_ENTRY_RESET";
export const DELETE_CASH_FAIL = "DELETE_CASH_ENTRY_FAIL";
export const UPDATE_CASH_REQUEST = "UPDATE_CASH_ENTRY_REQUEST";
export const UPDATE_CASH_SUCCESS = "UPDATE_CASH_ENTRY_SUCCESS";
export const UPDATE_CASH_RESET = "UPDATE_CASH_ENTRY_RESET";
export const UPDATE_CASH_FAIL = "UPDATE_CASH_ENTRY_FAIL";

export const TOTAL_CASH_REQUEST = "TOTAL_CASH_REQUEST"
export const TOTAL_CASH_SUCCESS = "TOTAL_CASH_SUCCESS"
export const TOTAL_CASH_FAIL = "TOTAL_CASH_FAIL"

export const ADD_CASH_REQUEST = "ADD_CASH_REQUEST"
export const ADD_CASH_SUCCES = "ADD_CASH_SUCCESS"
export const ADD_CASH_FAIL = "ADD_CASH_FAIL"
export const ADD_CASH_RESET = "ADD_CASH_RESET"

export const CLEAR_ERRORS = "CLEAR_ERRORS";
