export const MONTHLY_SALES_REQUEST = "MONTHLY_SALES_REQUEST";
export const MONTHLY_SALES_SUCCESS = "MONTHLY_SALES_SUCCESS";
export const MONTHLY_SALES_FAIL = "MONTHLY_SALES_FAIL";

export const PRODUCT_SALES_REQUEST = "PRODUCT_SALES_REQUEST";
export const PRODUCT_SALES_SUCCESS = "PRODUCT_SALES_SUCCESS";
export const PRODUCT_SALES_FAIL = "PRODUCT_SALES_FAIL";

export const MONTHLY_INCOME_REQUEST = "MONTHLY_INCOME_REQUEST";
export const MONTHLY_INCOME_SUCCESS = "MONTHLY_INCOME_SUCCESS";
export const MONTHLY_INCOME_FAIL = "MONTHLY_INCOME_FAIL";

export const MONTHLY_EXPENSES_REQUEST = "MONTHLY_EXPENSES_REQUEST";
export const MONTHLY_EXPENSES_SUCCESS = "MONTHLY_EXPENSES_SUCCESS";
export const MONTHLY_EXPENSES_FAIL = "MONTHLY_EXPENSES_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
