// Constants for Transaction Actions
export const NEW_TRANSACTION_REQUEST = "NEW_TRANSACTION_REQUEST";
export const NEW_TRANSACTION_SUCCESS = "NEW_TRANSACTION_SUCCESS";
export const NEW_TRANSACTION_FAIL = "NEW_TRANSACTION_FAIL";

export const GET_ALL_TRANSACTIONS_REQUEST = "GET_ALL_TRANSACTIONS_REQUEST";
export const GET_ALL_TRANSACTIONS_SUCCESS = "GET_ALL_TRANSACTIONS_SUCCESS";
export const GET_ALL_TRANSACTIONS_FAIL = "GET_ALL_TRANSACTIONS_FAIL";

export const GET_SINGLE_TRANSACTION_REQUEST = "GET_SINGLE_TRANSACTION_REQUEST";
export const GET_SINGLE_TRANSACTION_SUCCESS = "GET_SINGLE_TRANSACTION_SUCCESS";
export const GET_SINGLE_TRANSACTION_FAIL = "GET_SINGLE_TRANSACTION_FAIL";

export const UPDATE_TRANSACTION_REQUEST = "UPDATE_TRANSACTION_REQUEST";
export const UPDATE_TRANSACTION_SUCCESS = "UPDATE_TRANSACTION_SUCCESS";
export const UPDATE_TRANSACTION_FAIL = "UPDATE_TRANSACTION_FAIL";

export const DELETE_TRANSACTION_REQUEST = "DELETE_TRANSACTION_REQUEST";
export const DELETE_TRANSACTION_SUCCESS = "DELETE_TRANSACTION_SUCCESS";
export const DELETE_TRANSACTION_FAIL = "DELETE_TRANSACTION_FAIL";
export const DELETE_TRANSACTION_RESET = "DELETE_TRANSACTION_RESET";

export const PROCESS_TRANSACTION_REQUEST = "PROCESS_TRANSACTION_REQUEST";
export const PROCESS_TRANSACTION_SUCCESS = "PROCESS_TRANSACTION_SUCCESS";
export const PROCESS_TRANSACTION_FAIL = "PROCESS_TRANSACTION_FAIL";
export const PROCESS_TRANSACTION_RESET = "PROCESS_TRANSACTION_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
